[features]
seeds = false
skip-lint = false
[programs.localnet]
marinade_staking_demo = "DfHJpPQ7BNhGz9LNvohUgqFMDRqfLDeDXk8GKqnryNPT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yurushao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000

[test.validator]
ledger = ".anchor/test-ledger"
rpc_port = 8899
slots_per_epoch = "32"
# url = "https://api.devnet.solana.com"
url = "https://api.mainnet-beta.solana.com"

[[test.genesis]]
address = "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD"
program = "./fixtures/marinade.so"

# marinade state account
[[test.validator.clone]]
address = "8szGkuLTAux9XMgZ2vtY39jVSowEcpBfFfD8hXSEqdGC"

# mSOL token mint + authority (PDA)
[[test.validator.clone]]
address = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"
# [[test.validator.clone]]
# address = "3JLPCS1qM2zRw3Dp6V4hZnYHd4toMNPkNesXdX9tg6KM"

# Treasury
# Reserve SOL account (PDA)
[[test.validator.clone]]
address = "Du3Ysj1wKbxPKkuPPnvzQLQh8oMSVifs3jGZjJWXFmHN"

# Treasury mSOL account
[[test.validator.clone]]
address = "B1aLzaNMeFVAyQ6f3XbbUyKcH2YPHu2fqiEagmiF23VR"

# Liquidity-Pool 
# mSOL-SOL-LP mint
[[test.validator.clone]]
address = "LPmSozJJ8Jh69ut2WP3XmVohTjL4ipR18yiCzxrUmVj"

# Auth (PDA)
# [[test.validator.clone]]
# address = "HZsepB79dnpvH6qfVgvMpS738EndHw3qSHo4Gv5WX1KA"

# mSOL leg account
[[test.validator.clone]]
address = "7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE"

# mSOL leg authority
[[test.validator.clone]]
address = "EyaSjUtSgo9aRD1f8LWXwdvkpDTmXAW54yoSHZRF14WL"

# SOL leg account
[[test.validator.clone]]
address = "UefNb6z6yvArqe4cJHTXCqStRsKmWhGxnZzuHbikP5Q"
