[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
drift_cpi_demo = "3eqvCf482d2Z1C7DevfrQZpzmKUh687kt7yhgLYUaYzu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/drift_cpi_demo.ts"

[test]
startup_wait = 30000

[[test.genesis]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
program = "fixtures/programs/drift.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"

[[test.validator.account]] # drift state account
address = "5zpq7DvB6UdFFvpmBPspGPNfUGoBRRCE2HHg5u3gxcsN"
filename = "./fixtures/accounts/5zpq7DvB6UdFFvpmBPspGPNfUGoBRRCE2HHg5u3gxcsN.json"

[[test.validator.account]]
address = "BAtFj4kQttZRVep3UZS2aZRDixkGYgWsbqTBVDbnSsPF"
filename = "./fixtures/accounts/BAtFj4kQttZRVep3UZS2aZRDixkGYgWsbqTBVDbnSsPF.json"


[[test.validator.account]]
address = "3x85u7SWkmmr7YQGYhtjARgxwegTLJgkSLRprfXod6rh"
filename = "./fixtures/accounts/3x85u7SWkmmr7YQGYhtjARgxwegTLJgkSLRprfXod6rh.json"


[[test.validator.account]]
address = "DfYCNezifxAEsQbAJ1b3j6PX3JVBe8fu11KBhxsbw5d2"
filename = "./fixtures/accounts/DfYCNezifxAEsQbAJ1b3j6PX3JVBe8fu11KBhxsbw5d2.json"

[[test.validator.account]]
address = "GyyHYVCrZGc2AQPuvNbcP1babmU3L42ptmxZthUfD9q"
filename = "./fixtures/accounts/GyyHYVCrZGc2AQPuvNbcP1babmU3L42ptmxZthUfD9q.json"

[[test.validator.account]]
address = "HpMoKp3TCd3QT4MWYUKk2zCBwmhr5Df45fB6wdxYqEeh"
filename = "./fixtures/accounts/HpMoKp3TCd3QT4MWYUKk2zCBwmhr5Df45fB6wdxYqEeh.json"

[[test.validator.account]]
address = "8UJgxaiQx5nTrdDgph5FiahMmzduuLTLf5WmsPegYA6W"
filename = "./fixtures/accounts/8UJgxaiQx5nTrdDgph5FiahMmzduuLTLf5WmsPegYA6W.json"

[[test.validator.account]]
address = "En8hkHLkRe9d9DraYmBTrus518BvmVH448YcvmrFM6Ce"
filename = "./fixtures/accounts/En8hkHLkRe9d9DraYmBTrus518BvmVH448YcvmrFM6Ce.json"

[[test.validator.account]]
address = "6gMq3mRCKf8aP3ttTyYhuijVZ2LGi14oDsBbkgubfLB3"
filename = "./fixtures/accounts/6gMq3mRCKf8aP3ttTyYhuijVZ2LGi14oDsBbkgubfLB3.json"
