[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
realloc_demo = "FXFWZVRVm76Dw59UtcEGVWqno5C4U379sdo1PF423Z8A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yurushao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
